// Lista SATA MGAP Uruguay — Productos registrados para frutales
// Generado automáticamente desde ProdCultPlagas al 29-5-2026
// Total: 443 productos

export const PRODUCTOS_SATA_FRUTALES = [
  { nombre: "ALLEGIANCE 80 WP", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "FERAMINA", principioActivo: "2,4 D SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "GUSATHION M 35", principioActivo: "AZINFOS METIL", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "SUPRATHION 40", principioActivo: "METIDATION", tipoProducto: "Insecticida", carencia: 28 },
  { nombre: "MANZATE 200", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "POLYRAM DF", principioActivo: "METIRAM", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "DI-ON 80 FLOW", principioActivo: "DIURON", tipoProducto: "Herbicida", carencia: 60 },
  { nombre: "TALSTAR", principioActivo: "BIFENTRIN", tipoProducto: "Insecticida", carencia: 30 },
  { nombre: "ALSYSTIN 480 SC", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 10 },
  { nombre: "GLYFOSOL L-48", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "TARGET 720 SL", principioActivo: "MSMA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "PROCIPER", principioActivo: "CIPERMETRIN", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "CARBENDAFLOW 500", principioActivo: "CARBENDAZIMA", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "Dormex", principioActivo: "CIANAMIDA HIDROGENADA", tipoProducto: "Regulador de crecimiento", carencia: 0 },
  { nombre: "AZUFRUT 80 WDG", principioActivo: "AZUFRE", tipoProducto: "Fungicida", carencia: 28 },
  { nombre: "AGIL 100", principioActivo: "PROPAQUIZAFOP", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "BENCARB - L", principioActivo: "CARBENDAZIMA", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "CIPERMETRINA 25 AGRITEC", principioActivo: "CIPERMETRIN", tipoProducto: "Insecticida", carencia: 30 },
  { nombre: "MARSHALL 25 CE", principioActivo: "CARBOSULFAN", tipoProducto: "Insecticida-Acaricida", carencia: 15 },
  { nombre: "BENOMYL 50 SAUDU", principioActivo: "BENOMIL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "GLIFOTEC", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 21 },
  { nombre: "IMAZIL 75", principioActivo: "IMAZALIL SULFATO", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "MIRAGE 45 CE", principioActivo: "PROCLORAZ", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "DIMETOATO 40 FMC", principioActivo: "DIMETOATO", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "DIMET 40 EC", principioActivo: "DIMETOATO", tipoProducto: "Insecticida", carencia: 20 },
  { nombre: "MERPAN 80 DF", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "FOLPAN 80 DF", principioActivo: "FOLPET", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "FANAVID FLOWABLE", principioActivo: "OXICLORURO DE COBRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "FANAVID 85", principioActivo: "OXICLORURO DE COBRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "Sulfato de Cobre Emperador", principioActivo: "SULFATO DE COBRE PENTAHIDRATADO", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "PERECOPPER 50", principioActivo: "OXICLORURO DE COBRE", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "MANCOZEB AGRO REGIONAL", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "ZIRAM GRANUFLO", principioActivo: "ZIRAM", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "ACARISTOP 50 SC", principioActivo: "CLOFENTEZINA", tipoProducto: "Acaricida", carencia: 30 },
  { nombre: "DELAN WP 75", principioActivo: "DITIANON", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "CAPTOR", principioActivo: "GLUTEN DE MAIZ HIDROLIZADO", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "VAPOR GARD", principioActivo: "PINOLENO", tipoProducto: "Regulador de crecimiento", carencia: 1 },
  { nombre: "DANISIS", principioActivo: "FENPIROXIMATO", tipoProducto: "Acaricida", carencia: 14 },
  { nombre: "BORDELES AGROREGIONAL", principioActivo: "CALDO BORDELES (sulf.tetracúprico tricálcico)", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "CUPROUX 50", principioActivo: "OXIDO CUPROSO", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "STROBY SC", principioActivo: "KRESOXIM METIL", tipoProducto: "Fungicida", carencia: 45 },
  { nombre: "QUICK 250 EC", principioActivo: "PROPICONAZOL", tipoProducto: "Fungicida", carencia: 30 },
  { nombre: "TRIRAN FA", principioActivo: "CIHEXATIN", tipoProducto: "Acaricida", carencia: 30 },
  { nombre: "GIBERELAN 36", principioActivo: "ACIDO GIBERELICO", tipoProducto: "Regulador de crecimiento", carencia: 1 },
  { nombre: "ORIUS 25 EW", principioActivo: "TEBUCONAZOL", tipoProducto: "Fungicida", carencia: 20 },
  { nombre: "QUADRIS", principioActivo: "AZOXISTROBINA", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "MICROCAP M 450", principioActivo: "PARATION METIL", tipoProducto: "Insecticida", carencia: 35 },
  { nombre: "TRACER", principioActivo: "SPINOSAD (Espinosin A + Espinosin D)", tipoProducto: "Insecticida", carencia: 3 },
  { nombre: "PIONIER 4129", principioActivo: "aceite mineral", tipoProducto: "Insecticida", carencia: 1 },
  { nombre: "COBRE NORDOX SUPER 75 DF", principioActivo: "OXIDO CUPROSO", tipoProducto: "Fungicida", carencia: 30 },
  { nombre: "MERCAPTOTHION BELTRAME", principioActivo: "MALATION", tipoProducto: "Insecticida", carencia: 10 },
  { nombre: "IPRODIONEX 500", principioActivo: "IPRODIONA", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "CHECK PLUS", principioActivo: "GLIFOSATO ACIDO", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "RIMON 10 EC", principioActivo: "NOVALURON", tipoProducto: "Insecticida", carencia: 30 },
  { nombre: "PROZIM S.C.", principioActivo: "CARBENDAZIMA", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "TECTO 500 SC", principioActivo: "TIABENDAZOL", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "KARATE CON TECNOLOGIA ZEON", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 4 },
  { nombre: "OXI-CUP QUIMETAL WG", principioActivo: "OXICLORURO DE COBRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "CALDO BORDELES FANAPROQUI", principioActivo: "EQUIVALENTE EN COBRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "CALDO BORDELES FLOWABLE FANAPROQUI", principioActivo: "EQUIVALENTE EN COBRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "RAVYON 85 WP", principioActivo: "CARBARIL", tipoProducto: "Insecticida", carencia: 3 },
  { nombre: "NATURAL SHINE 2015-EU", principioActivo: "CERA CARNAUBA", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "SHIELD BRITE AC-2000", principioActivo: "CERA CARNAUBA", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "ZETA 500 SC", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "PAMPA", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "MYTHOS", principioActivo: "PIRIMETANIL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "SHIELD LIQUID DPA 31%", principioActivo: "DIFENILAMINA", tipoProducto: "Regulador de crecimiento", carencia: 0 },
  { nombre: "FACILY 18 EC CIBELES", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 14 },
  { nombre: "NOMOLT SC", principioActivo: "TEFLUBENZURON", tipoProducto: "Insecticida", carencia: 21 },
  { nombre: "TOMAHAWK 200 EC", principioActivo: "FLUROXIPIR-MEPTIL", tipoProducto: "Herbicida", carencia: 45 },
  { nombre: "TWISTER 25 EC", principioActivo: "CIPERMETRIN", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "CIBRANIL 500 F", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "DIURON AGRO REGIONAL", principioActivo: "DIURON", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "OXICLORURO DE COBRE AGRO REGIONAL", principioActivo: "OXICLORURO DE COBRE", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "PIONIER 2055", principioActivo: "aceite mineral", tipoProducto: "Insecticida-Acaricida", carencia: 0 },
  { nombre: "SANCOZEB 80 PM", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "TIABENDAZOL 500 CIBELES", principioActivo: "TIABENDAZOL", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "ALANTO 480 SC", principioActivo: "TIACLOPRID", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "ARDENT 50 SC", principioActivo: "KRESOXIM METIL", tipoProducto: "Fungicida", carencia: 35 },
  { nombre: "CAPTAN FLOW AGRO REGIONAL", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "SCORE 250 EC", principioActivo: "DIFENOCONAZOL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "MATCH EC", principioActivo: "LUFENURON", tipoProducto: "Insecticida", carencia: 21 },
  { nombre: "INTREPID SC", principioActivo: "METOXIFENOCIDA", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "AGROZEB 80 WP", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "AZOLE 5 SC", principioActivo: "HEXACONAZOL", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "MINALAN 20 SL", principioActivo: "ACETAMIPRID", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "VERTILAN 1.8 CE", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 7 },
  { nombre: "ZETAMIPRID 200 G/L SL", principioActivo: "ACETAMIPRID", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "ZERO 50 EC", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 4 },
  { nombre: "HELOSATE", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 21 },
  { nombre: "SULFOVIT 80 WDG", principioActivo: "AZUFRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "DODIN FLO", principioActivo: "DODINE", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "SANCOZEB 75 WDG", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "FLINT 50 WG", principioActivo: "TRIFLOXISTROBINA", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "SUPERZIM 50 SC", principioActivo: "CARBENDAZIMA", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "SYSTHANE 40 WP", principioActivo: "MICLOBUTANIL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "ULTRATION 40", principioActivo: "METIDATION", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "DECIS  FORTE 10 EC", principioActivo: "DELTAMETRIN", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "IMAZIL 50 CE", principioActivo: "IMAZALIL", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "DIAZIN 500 EC", principioActivo: "DIAZINON", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "ULTRATOP", principioActivo: "SIMAZINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "MAVRIK 240 EW", principioActivo: "tau FLUVALINATO", tipoProducto: "Insecticida-Acaricida", carencia: 28 },
  { nombre: "SYLLIT 400 SC", principioActivo: "DODINE", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "ABRIL 50 SC", principioActivo: "IPRODIONA", tipoProducto: "Fungicida", carencia: 3 },
  { nombre: "GLISERB LS NF", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "FULLBACK 480 S.C.", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 10 },
  { nombre: "SUPERQUAT", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "ACRITIN 60 F", principioActivo: "CIHEXATIN", tipoProducto: "Insecticida-Acaricida", carencia: 14 },
  { nombre: "GALIGAN 240 CE", principioActivo: "OXIFLUORFEN", tipoProducto: "Herbicida", carencia: 60 },
  { nombre: "SAU-GIB TABLETAS", principioActivo: "ACIDO GIBERELICO", tipoProducto: "Regulador de crecimiento", carencia: 0 },
  { nombre: "AGRIPROXYFEN", principioActivo: "PIRIPROXIFEN", tipoProducto: "Insecticida", carencia: 45 },
  { nombre: "AGROFURE", principioActivo: "AZUFRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "ACTIVO 250 EC", principioActivo: "DIFENOCONAZOL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "ESCOLTA", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 10 },
  { nombre: "PRODIGY 1.8 EC", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 14 },
  { nombre: "AMECTIN", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 10 },
  { nombre: "ORION 25 EW", principioActivo: "TEBUCONAZOL", tipoProducto: "Fungicida", carencia: 35 },
  { nombre: "FOCUS", principioActivo: "PIRIPROXIFEN", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "CIURON 500", principioActivo: "DIURON", tipoProducto: "Herbicida", carencia: 24 },
  { nombre: "MANCOZATE", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "SUNSPRAY 9 E", principioActivo: "aceite mineral", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "TRIAD 50 WG", principioActivo: "KRESOXIM METIL", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "LANNARK 250 EC", principioActivo: "DIFENOCONAZOL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "KIPPEN 5 SC", principioActivo: "HEXACONAZOL", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "SUPRA 40 EC", principioActivo: "METIDATION", tipoProducto: "Insecticida", carencia: 30 },
  { nombre: "ACETAMIPRID 20 SP", principioActivo: "ACETAMIPRID", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "TRIBEL MULTIUSO", principioActivo: "aceite mineral", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "LAMBDA 5 LSA", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "OVIS", principioActivo: "PIRIPROXIFEN", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "ACELAN 20", principioActivo: "ACETAMIPRID", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "VIGIA", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 28 },
  { nombre: "DIFLULIN CIB 48 SC®", principioActivo: "DIFLUBENZURON", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "RONDO AMONIO", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "RONDO", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "ORTHOCIDE 80 WDG", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "FOLDAN 80 WDG", principioActivo: "FOLPET", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "UTHANE 80%", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "ESCOZATE", principioActivo: "DIFENOCONAZOL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "SULFAGRO 80% WDG", principioActivo: "AZUFRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "POWER RANGO", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "FATTOR 25 EC", principioActivo: "CIPERMETRIN", tipoProducto: "Insecticida", carencia: 30 },
  { nombre: "NION 48 S.C.", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 28 },
  { nombre: "PRODURE 50 S.C.", principioActivo: "PROCIMIDONA", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "PANZER GOLD", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "ULTRAVIN 4 L", principioActivo: "CARBARIL", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "VENTHOS S.C.", principioActivo: "PIRIMETANIL", tipoProducto: "Fungicida", carencia: 28 },
  { nombre: "ABAMECTINA 1.8 AGROREGIONAL", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "SEIZER 10 EC", principioActivo: "BIFENTRIN", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "ANA", principioActivo: "ACIDO L-NAFTIL ACÉTICO SAL POTÁSICO", tipoProducto: "Regulador de crecimiento", carencia: 2 },
  { nombre: "UTHANE 75 DF", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "CYANAMIDA HIDROGENADA AGROREGIONAL", principioActivo: "CIANAMIDA HIDROGENADA", tipoProducto: "Regulador de crecimiento", carencia: 30 },
  { nombre: "CAPTAN 80 AGROREGIONAL", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "PHALTAN 80 WDG", principioActivo: "FOLPET", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "ISOMATTE CTT", principioActivo: "DODECADIENOL", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "ISOMATE OFM TT", principioActivo: "Z-8-DODECEN-1-IL ACETATO", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "PYRUS 400 SC", principioActivo: "PIRIMETANIL", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "MANCOZEB AGRO REGIONAL 75 WDG", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "UNIQUAT", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "BANCO 500 FW", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "MANZATE 75 DF", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "PERRINPIT", principioActivo: "CALCIO, CLORURO", tipoProducto: "Regulador de crecimiento", carencia: 0 },
  { nombre: "GLISERB SUPRA III", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "ASPILAN 20 SL", principioActivo: "ACETAMIPRID", tipoProducto: "Insecticida", carencia: 3 },
  { nombre: "DESTROYER", principioActivo: "PIRIPROXIFEN", tipoProducto: "Insecticida", carencia: 45 },
  { nombre: "SAUQUAT SUPER", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 15 },
  { nombre: "EFUZIN 400 SC", principioActivo: "DODINE", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "BAICEN", principioActivo: "MATRINE", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "PRO FOLPET 50 SC", principioActivo: "FOLPET", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "PRO CAPTAN 50 SC", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "YPF CURAFRUTAL LV", principioActivo: "aceite mineral", tipoProducto: "Insecticida-Acaricida", carencia: 30 },
  { nombre: "IMIDAN 70", principioActivo: "FOSMET", tipoProducto: "Insecticida-Acaricida", carencia: 20 },
  { nombre: "CENTINELA 75 DF", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "SAUTOP 90 WG", principioActivo: "SIMAZINA", tipoProducto: "Herbicida", carencia: 45 },
  { nombre: "SPONSOR 50 WG", principioActivo: "KRESOXIM METIL", tipoProducto: "Fungicida", carencia: 35 },
  { nombre: "UNIZEB", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "UNIZEB GOLD", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "BELT", principioActivo: "FLUBENDIAMIDE", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "BESTOX", principioActivo: "BIFENTRIN", tipoProducto: "Insecticida", carencia: 30 },
  { nombre: "CAPTURE 100", principioActivo: "BIFENTRIN", tipoProducto: "Insecticida", carencia: 30 },
  { nombre: "ALLEGIANCE 80 WG", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "SOUFRE 80 WG", principioActivo: "AZUFRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "CHECK MAX", principioActivo: "GLIFOSATO, SAL MONOAMÓNICA", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "ZIMBA 80 WP", principioActivo: "TERBACILO", tipoProducto: "Herbicida", carencia: 3 },
  { nombre: "CHECKMATE PUFFER CM-OFM", principioActivo: "DODECADIENOL", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "CIBENCARB 500 FLOW", principioActivo: "CARBENDAZIMA", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "SUPERLATE", principioActivo: "BENOMIL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "FACILY 3,6", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 14 },
  { nombre: "MICROTHIOL SPECIAL DISPERSS", principioActivo: "AZUFRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "CARBARILUM", principioActivo: "CARBARIL", tipoProducto: "Insecticida", carencia: 5 },
  { nombre: "CERATITIS TRAP", principioActivo: "PROTEINAS HIDROLIZADAS", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "RIMON SUPRA 100 SC", principioActivo: "NOVALURON", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "RIDOWN", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "GEA GLIFOSATO AMONICO 75.7 SG", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "BRACONIL 720 SC", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "PILARICH 750 WP", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "F.T. FOL 25 SC", principioActivo: "FLUTRIAFOL", tipoProducto: "Fungicida", carencia: 30 },
  { nombre: "CHECK GOLD", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "PRODINOLEO", principioActivo: "ACEITE DE SOJA", tipoProducto: "Insecticida-Acaricida", carencia: 0 },
  { nombre: "PANGARE", principioActivo: "FLUROXIPIR-MEPTIL", tipoProducto: "Herbicida", carencia: 40 },
  { nombre: "GEA GLIFOSATO POTASICO 66 SL", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "AGROCAP 80 WDG", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "SPLENDOR 480 S.C", principioActivo: "TIACLOPRID", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "DELEGATE", principioActivo: "ESPINETORAM", tipoProducto: "Insecticida", carencia: 1 },
  { nombre: "ESKOBA FULL  II", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "RIDOWN PS FULL", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "GENFOSATO", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "GLIFOWEED ® PLATINUM", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "KILLER 5 EC", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "RELAMPAGO 500 S.C", principioActivo: "DODINE", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "DIMETOFF 40 SC", principioActivo: "DIMETOATO", tipoProducto: "Insecticida", carencia: 21 },
  { nombre: "GENQUAT", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 15 },
  { nombre: "KARMEX 90 WDG", principioActivo: "DIURON", tipoProducto: "Herbicida", carencia: 90 },
  { nombre: "ZENITH", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 1 },
  { nombre: "RHINO 75 WDG", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "TRIBOT 50 F", principioActivo: "IPRODIONA", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "FOLPET TAFIREL", principioActivo: "FOLPET", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "FRUITGARD PIR 400", principioActivo: "PIRIMETANIL", tipoProducto: "Fungicida", carencia: 28 },
  { nombre: "FOLP 80 WDG", principioActivo: "FOLPET", tipoProducto: "Fungicida", carencia: 80 },
  { nombre: "AZUFRATE 80 DF", principioActivo: "AZUFRE", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "CAPTAN TAFIREL", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "RIAN", principioActivo: "TIACLOPRID", tipoProducto: "Insecticida", carencia: 30 },
  { nombre: "RIDOWN 88.8 XTRA", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "RAINQUAT", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "CALDO BORDELES VALLES", principioActivo: "CALDO BORDELES (sulf.tetracúprico tricálcico)", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "TRILLA XTRA", principioActivo: "DIURON", tipoProducto: "Herbicida", carencia: 45 },
  { nombre: "GEA TRIFLUMURON 48 SC", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 28 },
  { nombre: "MAXWEED 200 SL", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "GLISERB SUN", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "Novomectin 228 EC", principioActivo: "BENZOATO EMAMECTINA", tipoProducto: "Insecticida", carencia: 3 },
  { nombre: "GENMECTIN", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 14 },
  { nombre: "GLAMOUR", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 5 },
  { nombre: "OSADO", principioActivo: "METOXIFENOCIDA", tipoProducto: "Insecticida", carencia: 3 },
  { nombre: "GENADOM", principioActivo: "DIFENOCONAZOL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "AVENGER", principioActivo: "METOXIFENOCIDA", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "IPRODION 500 SC", principioActivo: "IPRODIONA", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "MANZATE RAINCOAT 75 DF", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "MANZATE RAINCOAT 80 WP", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 10 },
  { nombre: "AZUKA", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "BASTNATE", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "BLINDAR 200 SC", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 1 },
  { nombre: "STAR K", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "PREMIER 480 SC", principioActivo: "TIACLOPRID", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "DIQUAT SOLARIS 200 SL", principioActivo: "DICUAT SAL DIBROMURO", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "GENCOZEB", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "MAESTRO 24% WG", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 21 },
  { nombre: "PONCHO 70 WP", principioActivo: "PROPINEB", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "ABAMECTINA CALISTER 3.6 CE", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 14 },
  { nombre: "MADEX TWIN", principioActivo: "GRANULOVIRUS DE CYDIA POMONELLA(CpGv)", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "AKARIL 50 SC", principioActivo: "FENPIROXIMATO", tipoProducto: "Acaricida", carencia: 21 },
  { nombre: "UNO 5 CS", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "TANCAP XTRA", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "SISTEMA 80 WP", principioActivo: "FOSETIL- ALUMINIO", tipoProducto: "Fungicida", carencia: 35 },
  { nombre: "ARROW 240 EC", principioActivo: "CLETODIN", tipoProducto: "Herbicida", carencia: 8 },
  { nombre: "FLECHA 240 CE", principioActivo: "CLETODIN", tipoProducto: "Herbicida", carencia: 8 },
  { nombre: "TRIBOT 50 WP", principioActivo: "IPRODIONA", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "LA TIJERETA BOX", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "ENVIRO-SHIELD", principioActivo: "PINOLENO", tipoProducto: "Regulador de crecimiento", carencia: 1 },
  { nombre: "TRADITION ACEITE MINERAL", principioActivo: "aceite mineral", tipoProducto: "Insecticida-Acaricida", carencia: 0 },
  { nombre: "ABAMET", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 15 },
  { nombre: "SUNSPRAY SUPREME", principioActivo: "aceite mineral", tipoProducto: "Insecticida-Acaricida", carencia: 0 },
  { nombre: "NOVOMECTIN 200 EC", principioActivo: "BENZOATO EMAMECTINA", tipoProducto: "Insecticida", carencia: 3 },
  { nombre: "CLORANTE 20 SC", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "IMPROSATE FULL K", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 21 },
  { nombre: "PRIAXOR", principioActivo: "PIRACLOSTROBINA", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "SELENIUM 75 WDG", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 21 },
  { nombre: "FYSIUM®", principioActivo: "1-METILCICLOPROPENO (1-MCP)", tipoProducto: "Regulador de crecimiento", carencia: 0 },
  { nombre: "ZIRAM TAFIREL", principioActivo: "ZIRAM", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "GLISERB SUN SG", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "TRIBER XTRA", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 28 },
  { nombre: "CUPROFIX 40 WDG", principioActivo: "SULFATO DE COBRE TRIBÁSICO", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "POTENZA GOLD", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 24 },
  { nombre: "KEMAZON", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "REQUIEM 75 WDG", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "GLYFOSOL GOLD", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "TOP-OIL", principioActivo: "aceite mineral", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "PLACA DEGESCH", principioActivo: "FOSFURO DE MAGNESIO", tipoProducto: "Insecticida-Acaricida", carencia: 0 },
  { nombre: "RE TAIN", principioActivo: "AMINOETOXIVINILGLICINA", tipoProducto: "Regulador de crecimiento", carencia: 7 },
  { nombre: "CLORANTE 20 FE", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 1 },
  { nombre: "CLORANTE 75 WG", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 1 },
  { nombre: "MAXCEL", principioActivo: "BENCILADENINA (BAP)", tipoProducto: "Regulador de crecimiento", carencia: 0 },
  { nombre: "EXTRAQUAT", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 48 },
  { nombre: "RYNAGEN 200 SC", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 1 },
  { nombre: "BRACONIL 72% FLOW", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "MASTEROLE", principioActivo: "METOXIFENOCIDA", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "LIFELINE", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 35 },
  { nombre: "NAVEX", principioActivo: "TIACLOPRID", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "ALCANCE 250 SC", principioActivo: "TIACLOPRID", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "BISECT", principioActivo: "BIFENTRIN", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "TRIBOT 50 SC", principioActivo: "IPRODIONA", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "GLIFOSATO GROWING", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "GLISA SUPRA II FE", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "WP SUPRA II FE", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "GLISA SUN FE", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "CAMPO-GLUF 200 SL", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 70 },
  { nombre: "WP SUN FE", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "STRONG 10 SC", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "MOVENTO®", principioActivo: "SPIROTETRAMAT", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "METEOR 288 EC", principioActivo: "FLUROXIPIR-MEPTIL", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "GEA ABAMECTINA 3.6 EC", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 14 },
  { nombre: "GLYFOSOL MAX 88.8", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "TIFON", principioActivo: "LUFENURON", tipoProducto: "Insecticida", carencia: 35 },
  { nombre: "GLUFEX 300 SL", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 35 },
  { nombre: "SPLAT OFM", principioActivo: "(E)-8-DODECENIL ACETATO", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "SPLAT CYDIA", principioActivo: "(E,E) - 8 ,10- DODECADIENOL", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "FINAL 200 SL", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 70 },
  { nombre: "PULSAR GOLD", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "GRASIDIM FULL", principioActivo: "CLETODIN", tipoProducto: "Herbicida", carencia: 8 },
  { nombre: "PAUKER MAX", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "ZILTOP 70% WG", principioActivo: "METIL TIOFANATO", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "FIXTURE 500 SC", principioActivo: "DIFENOCONAZOL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "FUNGI-ZEB 75 WDG", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "PYRIPROXYFEN CEM", principioActivo: "PIRIPROXIFEN", tipoProducto: "Insecticida", carencia: 48 },
  { nombre: "ACAREX PLUS", principioActivo: "HEXITIAZOX", tipoProducto: "Acaricida", carencia: 30 },
  { nombre: "FLUMIO 480 SC", principioActivo: "FLUMIOXAZINA", tipoProducto: "Herbicida", carencia: 20 },
  { nombre: "REVELACION", principioActivo: "BOSCALID", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "AGROXIPIR 288 EC", principioActivo: "FLUROXIPIR-MEPTIL", tipoProducto: "Herbicida", carencia: 45 },
  { nombre: "BLINDAR 75 WG", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "POWER ALB", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "CLOSER", principioActivo: "SULFOXAFLOR", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "AGROZEB FLO", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "ATHION 45 EC", principioActivo: "MALATION", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "DINON 50 EC", principioActivo: "DIAZINON", tipoProducto: "Insecticida", carencia: 15 },
  { nombre: "GLIFULL-K 83.3 SG", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "PILARXONE", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 24 },
  { nombre: "FUNGICAP 480 SC", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "PARAQUAT 276 TAMPA", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "CLETOSUPER", principioActivo: "CLETODIN", tipoProducto: "Herbicida", carencia: 60 },
  { nombre: "OBULUS", principioActivo: "LAMBDA CIALOTRINA", tipoProducto: "Insecticida", carencia: 21 },
  { nombre: "ACE 20 SL", principioActivo: "ACETAMIPRID", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "FULL SOJA 480 G/L", principioActivo: "FLUMIOXAZINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "UNICORN", principioActivo: "AZUFRE", tipoProducto: "Fungicida", carencia: 35 },
  { nombre: "POTENZA ULTRA II", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "SINBAR 80 WDG", principioActivo: "TERBACILO", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "BRANDO", principioActivo: "METIL TIOFANATO", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "GLIFUMAX", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "GLIFUPOWER", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "CLORONIL 50", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 30 },
  { nombre: "PANZER GOLD ALB", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "STAR DMA 80 SG", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 21 },
  { nombre: "FLUMITOP 480 SC", principioActivo: "FLUMIOXAZINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "WALLOPER", principioActivo: "FLUROXIPIR-MEPTIL", tipoProducto: "Herbicida", carencia: 45 },
  { nombre: "1-MCP POWER", principioActivo: "1-METILCICLOPROPENO (1-MCP)", tipoProducto: "Regulador de crecimiento", carencia: 0 },
  { nombre: "SIMAPLEX 90 WDG", principioActivo: "SIMAZINA", tipoProducto: "Herbicida", carencia: 45 },
  { nombre: "BOTRIX", principioActivo: "BOSCALID", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "TOTAL PS 22", principioActivo: "aceite mineral", tipoProducto: "Insecticida-Acaricida", carencia: 0 },
  { nombre: "FLAME 200 SL", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "MICROGLIF K", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 21 },
  { nombre: "FLUROXYPYR FORTE 480", principioActivo: "FLUROXIPIR-MEPTIL", tipoProducto: "Herbicida", carencia: 45 },
  { nombre: "CIDETRAK OFM-L", principioActivo: "Z-8-DODECEN-1-IL ACETATO", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "GEA PARAQUAT 200 SL", principioActivo: "DICLORURO DE PARAQUAT", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "RESTARTER", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 21 },
  { nombre: "CLOROTALONIL SOLARIS 720 SC", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "STRADA 88 SG", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 70 },
  { nombre: "XYFEN", principioActivo: "PIRIPROXIFEN", tipoProducto: "Insecticida", carencia: 21 },
  { nombre: "RIVAL 90 WDG", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "GEA HALOXIFOP METIL 540 EC", principioActivo: "HALOXIFOP-P-METIL", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "FLUMYZIN 500 SC", principioActivo: "FLUMIOXAZINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "POINTER 500", principioActivo: "FLUTRIAFOL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "DITHIALAN 75 WDG", principioActivo: "DITIANON", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "BOSPYR", principioActivo: "BOSCALID", tipoProducto: "Fungicida", carencia: 1 },
  { nombre: "FIPRO-MAX", principioActivo: "FIPRONIL", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "TRIFLUMIC 480 SC", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 28 },
  { nombre: "BETK - 03", principioActivo: "BACILLUS THURINGIENSIS CEPA 1", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "KUNG-FU 75", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "GEA GLIFOSATO AMONICO 88.8 SG", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "GEA MANCOZEB 80 WP", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "AGROZEB 75 WG", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "TURICIB 32 WP", principioActivo: "Bacillus thuringiensis var. Kurstaki cepa CGMMCC No. 1.1014", tipoProducto: "Insecticida", carencia: 3 },
  { nombre: "AVERMIC 18", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 3 },
  { nombre: "ARTEMIS", principioActivo: "PIRIPROXIFEN", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "GEA CLETHODIM 240 EC", principioActivo: "CLETODIN", tipoProducto: "Herbicida", carencia: 65 },
  { nombre: "ESCOLTA 80 WG", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 28 },
  { nombre: "CLOROMIC 720 SC", principioActivo: "CLOROTALONIL", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "SLOW MAT 150 OD", principioActivo: "SPIROTETRAMAT", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "CLEANOUT", principioActivo: "DICUAT SAL DIBROMURO", tipoProducto: "Herbicida", carencia: 3 },
  { nombre: "AZUKA FULL", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "IMPROSATE 88.8", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "STRADA 200 SL", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 70 },
  { nombre: "CLORANTRAMIC 75 WG", principioActivo: "CLORANTRANILIPROL", tipoProducto: "Insecticida", carencia: 14 },
  { nombre: "MANCOMIC 430 SC", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 21 },
  { nombre: "MESSENGER 120 EC", principioActivo: "SPIROTETRAMAT", tipoProducto: "Insecticida", carencia: 21 },
  { nombre: "DIQUAT TAFIREL", principioActivo: "DICUAT SAL DIBROMURO", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "LUNA TRANQUILITY SC 500", principioActivo: "PIRIMETANIL", tipoProducto: "Fungicida", carencia: 72 },
  { nombre: "PROZIRAM 80%", principioActivo: "ZIRAM", tipoProducto: "Fungicida", carencia: 20 },
  { nombre: "ISOMATE CM FLEX", principioActivo: "DODECANOL", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "AVANT 70 WDG", principioActivo: "SAFLUFENACIL", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "FANAZEB 80 PM", principioActivo: "MANCOZEB", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "SEQUAT 200 SL", principioActivo: "DICUAT SAL DIBROMURO", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "CIDETRAK CM OFM DUO MESO", principioActivo: "Z-8-DODECEN-1-IL ACETATO", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "FANACUP 75", principioActivo: "OXIDO CUPROSO", tipoProducto: "Fungicida", carencia: 30 },
  { nombre: "CHECKMATE PUFFER OFM", principioActivo: "(Z)-8-DODECEN-1-YL-ACETATE", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "FOLTAN 80 WG", principioActivo: "FOLPET", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "DECCOFLUDI 230 SC", principioActivo: "FLUDIOXONILO", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "COLBAN 5 G", principioActivo: "METALDEHIDO", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "GS GLIFOSATO DMA 608 G/L SL", principioActivo: "GLIFOSATO SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "GS GLIFOSATO 75,7% SG", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "CAMPERO GOLD 88 SG", principioActivo: "GLIFOSATO, SAL MONOAMÓNICA", tipoProducto: "Herbicida", carencia: 21 },
  { nombre: "WEEDFIRE", principioActivo: "DICUAT SAL DIBROMURO", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "MCPA 75 TAFIREL", principioActivo: "MCPA, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 30 },
  { nombre: "NO SCALD DPA", principioActivo: "DIFENILAMINA", tipoProducto: "Regulador de crecimiento", carencia: 2 },
  { nombre: "GLISERB SUN SG II", principioActivo: "GLIFOSATO SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 24 },
  { nombre: "GLIFA DMA 608 SL", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "ALRAS", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "TANCAT", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 5 },
  { nombre: "DECCO TBZ 50 SC", principioActivo: "TIABENDAZOL", tipoProducto: "Fungicida", carencia: 0 },
  { nombre: "PIRIPROX AGRO", principioActivo: "PIRIPROXIFEN", tipoProducto: "Insecticida", carencia: 45 },
  { nombre: "GLIFOHODO 662", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "GLIFOHODO 888", principioActivo: "GLIFOSATO ACIDO", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "GLIFOHODO DMA", principioActivo: "GLIFOSATO, SAL DIMETILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "GLIFA 75.7 SG", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "IMPIDE", principioActivo: "ACIDOS GRASOS, SAL POTASICA", tipoProducto: "Insecticida-Acaricida", carencia: 0 },
  { nombre: "ABAMECTIN 72 EC NORTOX", principioActivo: "ABAMECTINA", tipoProducto: "Insecticida-Acaricida", carencia: 14 },
  { nombre: "PILARSATO SUPER", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "GLUFHODO 200", principioActivo: "GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 21 },
  { nombre: "MEGA-GLI K", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "MEGA - GLI IPA", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "CLETOFIN", principioActivo: "CLETODIN", tipoProducto: "Herbicida", carencia: 60 },
  { nombre: "CHECK TOP", principioActivo: "GLIFOSATO, SAL MONOAMÓNICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "AGROMURON", principioActivo: "TRIFLUMURON", tipoProducto: "Insecticida", carencia: 10 },
  { nombre: "ZETAMIPRID 70 WG", principioActivo: "ACETAMIPRID", tipoProducto: "Insecticida", carencia: 7 },
  { nombre: "MEGA-GLI 88.8", principioActivo: "GLIFOSATO, SAL AMONICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "MOLUSQUICIDA CLARTEX", principioActivo: "METALDEHIDO", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "TEMPO 420 SC", principioActivo: "PYROXASULFONE", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "DIQUAFIN", principioActivo: "DICUAT SAL DIBROMURO", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "GLIFULL-K 66 SL", principioActivo: "GLIFOSATO, SAL POTÁSICA", tipoProducto: "Herbicida", carencia: 7 },
  { nombre: "HALVETIC", principioActivo: "GLIFOSATO, SAL ISOPROPILAMINA", tipoProducto: "Herbicida", carencia: 45 },
  { nombre: "NATURCOVER CONSERVACION EXTRA", principioActivo: "ESTERES DE ACIDOS GRASOS CON SACAROSA", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "NOGRAM 540 EC", principioActivo: "HALOXIFOP-P-METIL", tipoProducto: "Herbicida", carencia: 15 },
  { nombre: "BRAVO 48", principioActivo: "PYROXASULFONE", tipoProducto: "Herbicida", carencia: 0 },
  { nombre: "LIFELINE MEGA", principioActivo: "L - GLUFOSINATO DE AMONIO", tipoProducto: "Herbicida", carencia: 70 },
  { nombre: "FORZA CE", principioActivo: "SAFLUFENACIL", tipoProducto: "Herbicida", carencia: 95 },
  { nombre: "SEPTA", principioActivo: "SPINOSAD (Espinosin A + Espinosin D)", tipoProducto: "Insecticida", carencia: 1 },
  { nombre: "GLIFOTEC 88.8 SG", principioActivo: "GLIFOSATO, SAL MONOAMÓNICA", tipoProducto: "Herbicida", carencia: 14 },
  { nombre: "FUNCAP 80 WG", principioActivo: "CAPTAN", tipoProducto: "Fungicida", carencia: 7 },
  { nombre: "AGROFOLPET 80", principioActivo: "FOLPET", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "ESTEN 80", principioActivo: "MEZCLA DE GLICERIDOS DE ACEITE VEGETAL, JABONES DE POTASIO Y SUCROGLICERIDOS", tipoProducto: "Insecticida-Acaricida", carencia: 0 },
  { nombre: "FIPROMIC RB", principioActivo: "FIPRONIL", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "MIBELYA", principioActivo: "FLUXAPIROXAD", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "MAGISTER 200 SC", principioActivo: "FENAZAQUIN", tipoProducto: "Acaricida", carencia: 30 },
  { nombre: "DECCOPYR 40 SC", principioActivo: "PIRIMETANIL", tipoProducto: "Fungicida", carencia: 14 },
  { nombre: "CITRASHINE VEGETAL", principioActivo: "CERA CARNAUBA", tipoProducto: "Insecticida", carencia: 0 },
  { nombre: "OMEGA", principioActivo: "PIRACLOSTROBINA", tipoProducto: "Fungicida", carencia: 15 },
  { nombre: "FINACIL XTRA", principioActivo: "SAFLUFENACIL", tipoProducto: "Herbicida", carencia: 20 },
];
